name: LogBlock
version: '1.51'
author: DiddiZ
website: http://www.diddiz.de/minecraft/
main: de.diddiz.LogBlock.LogBlock
description: Logs blocks.
softdepend: [Spout, LogBlockQuestioner, Permissions, WorldEdit]
commands:
  lb:
    description: 'LogBlock commands.'
    usage: 'Usage: /<command> help'
    aliases: []
permissions:
    logblock.*:
        description: Gives access to all LogBlock commands
        children:
            logblock.lookup: true
            logblock.rollback: true
            logblock.clearlog: true
            logblock.hide: true
            logblock.tp: true
            logblock.me: true
            logblock.ignoreRestrictions: true
            logblock.spawnTools: true
    logblock.lookup:
        description: 'Grants access to /lb lookup commands and allows defining custom tool queries'
        default: op
    logblock.rollback:
        description: 'Allows rollback, redo and write logfiles'
        default: op
    logblock.clearlog:
        description: 'Allows to use /lb clearlog'
        default: op
    logblock.hide:
        description: 'Allows to hide from logging'
        default: op
    logblock.tp:
        description: 'Allows to use /lb tp'
        default: op
    logblock.tp:
        description: 'Allows to use /lb tp'
        default: op
    logblock.me:
        description: 'Allows to see oneselfs stats with /lb me'
        default: true
    logblock.ignoreRestrictions:
        description: 'Allows to ignore the rollback restrictions rollback.maxTime and rollback.maxArea'
        default: op
    logblock.spawnTools:
        description: 'Allows to spawn tools'
        default: true